name = "mentorshipsite"
compatibility_date = "2026-05-10"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = ".next"

[env.production]
name = "mentorshipsite"
compatibility_date = "2026-05-10"
compatibility_flags = ["nodejs_compat"]
